name:                ch1
version:             0.1.0.0
github:              "githubuser/ch1"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- readme.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the readme.md file.
description:         Please see the readme on GitHub at <https://github.com/githubuser/ch1#readme>

dependencies:
- base >= 4.7 && < 5
- Euterpea
- optparse-applicative

library:
  source-dirs: src

executables:
  ch1-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ch1

tests:
  ch1-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ch1
    - hspec
